In [6]:
import numpy as np

In [7]:
arr = np.array([1, 2, 3, 4, 5])
arr


array([1, 2, 3, 4, 5])

In [8]:
arr=np.arange(0,10,1)#arr with in a range
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
ln=np.linspace(0,100,10)
ln

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [10]:
ran=np.random.rand(4)#for a random variable

In [11]:
ran

array([0.02020432, 0.83878715, 0.39112742, 0.49939318])

In [12]:
z=np.zeros(5)#for all zeroes 

In [13]:
z

array([0., 0., 0., 0., 0.])

In [14]:
ar2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
z1=np.zeros((5,5))

In [17]:
z1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
z2=np.ones((5,5),dtype=np.int32)

In [19]:
z2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [20]:
I=np.eye(5)

In [21]:
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
R1=np.random.rand(4,5)

In [23]:
R1

array([[0.36377569, 0.35033471, 0.55838798, 0.52956606, 0.40324419],
       [0.4531093 , 0.83758653, 0.99888052, 0.07034876, 0.8983152 ],
       [0.20567456, 0.19276821, 0.68634872, 0.46674309, 0.60944954],
       [0.97845522, 0.70630418, 0.70047693, 0.4880687 , 0.73288212]])

In [24]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
print(arr.size)

10


In [27]:
print(ar2.size)

9


In [28]:
print(arr.shape)

(10,)


In [29]:
print(ar2.shape)

(3, 3)


# Operations in array

copy

sort

reshape

In [30]:
ar3=np.copy(ar2)

In [31]:
ar3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
ar3[2,2]=10

In [33]:
ar3


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [34]:
ar3[1,2]=12

In [35]:
ar3[1,0]=10

In [36]:
ar3.sum()

np.int64(58)

In [37]:
ar3=np.sort(ar3,axis=0)

In [38]:
ar3

array([[ 1,  2,  3],
       [ 7,  5, 10],
       [10,  8, 12]])

In [39]:
ar3=np.sort(ar3,axis=1)

In [40]:
ar3

array([[ 1,  2,  3],
       [ 5,  7, 10],
       [ 8, 10, 12]])

In [46]:
ar4=np.concatenate((ar3,ar3),axis=0)
ar4

array([[ 1,  2,  3],
       [ 5,  7, 10],
       [ 8, 10, 12],
       [ 1,  2,  3],
       [ 5,  7, 10],
       [ 8, 10, 12]])

In [47]:
ar4=np.concatenate((ar3,ar3),axis=1)
ar4

array([[ 1,  2,  3,  1,  2,  3],
       [ 5,  7, 10,  5,  7, 10],
       [ 8, 10, 12,  8, 10, 12]])

In [52]:
np.split (ar4,2,axis=1)

[array([[ 1,  2,  3],
        [ 5,  7, 10],
        [ 8, 10, 12]]),
 array([[ 1,  2,  3],
        [ 5,  7, 10],
        [ 8, 10, 12]])]

In [53]:
ar6=np.split(ar4,3)

In [54]:
ar6

[array([[1, 2, 3, 1, 2, 3]]),
 array([[ 5,  7, 10,  5,  7, 10]]),
 array([[ 8, 10, 12,  8, 10, 12]])]

In [55]:
ar6[0]

array([[1, 2, 3, 1, 2, 3]])

In [58]:
ar6[2]

array([[ 8, 10, 12,  8, 10, 12]])

# scalar addition

add, subtract,multiply,divide,power

In [60]:
ar6

[array([[1, 2, 3, 1, 2, 3]]),
 array([[ 5,  7, 10,  5,  7, 10]]),
 array([[ 8, 10, 12,  8, 10, 12]])]

In [61]:
np.add(ar6,1)

array([[[ 2,  3,  4,  2,  3,  4]],

       [[ 6,  8, 11,  6,  8, 11]],

       [[ 9, 11, 13,  9, 11, 13]]])

In [63]:
np.subtract(ar6,1)



array([[[ 0,  1,  2,  0,  1,  2]],

       [[ 4,  6,  9,  4,  6,  9]],

       [[ 7,  9, 11,  7,  9, 11]]])

In [64]:
np.multiply(ar6,3)

array([[[ 3,  6,  9,  3,  6,  9]],

       [[15, 21, 30, 15, 21, 30]],

       [[24, 30, 36, 24, 30, 36]]])

In [70]:
ar7= np.divide(ar6,2)

In [71]:
ar7

array([[[0.5, 1. , 1.5, 0.5, 1. , 1.5]],

       [[2.5, 3.5, 5. , 2.5, 3.5, 5. ]],

       [[4. , 5. , 6. , 4. , 5. , 6. ]]])

In [72]:
np.floor(ar7)

array([[[0., 1., 1., 0., 1., 1.]],

       [[2., 3., 5., 2., 3., 5.]],

       [[4., 5., 6., 4., 5., 6.]]])

In [73]:
np.round(ar7)

array([[[0., 1., 2., 0., 1., 2.]],

       [[2., 4., 5., 2., 4., 5.]],

       [[4., 5., 6., 4., 5., 6.]]])

# STATISTICS

In [74]:
np.mean(ar4)

np.float64(6.444444444444445)

In [75]:
np.median(ar4)


np.float64(7.0)

In [77]:
np.mean(ar4,axis=1)

array([ 2.        ,  7.33333333, 10.        ])

In [78]:
np.median(ar4,axis=1)

array([ 2.,  7., 10.])

In [79]:
np.max(ar4,axis=1)

array([ 3, 10, 12])