In [105]:
import numpy as np

In [106]:
ar2=np.array([[85,90,78],[92,88,95],[76,95,85],[90,85,92],[88,76,89]])

In [107]:
ar2

array([[85, 90, 78],
       [92, 88, 95],
       [76, 95, 85],
       [90, 85, 92],
       [88, 76, 89]])

In [108]:
np.mean (ar2,axis=1)#To find the means score of each subject.

array([84.33333333, 91.66666667, 85.33333333, 89.        , 84.33333333])

In [109]:
np.median (ar2,axis=1)#To find median score of each subject.

array([85., 92., 85., 90., 88.])

In [110]:
ar2=np.array([[85,90,78],[92,88,95],[76,95,85],[90,85,92],[88,76,89]])

sum = np.sum(ar2,axis=1)#TO FIND A SUM OF THE SCORE OF THE STUDENTS
print(sum)#PRINT SUM
highest_index= np.argmax(sum)#TO FIND MAX SUM
highest_scores = ar2[highest_index]#TO FIND WHICH INDEX HAVING HIGH SCORE
print("scores of the student with the highest total score:",highest_scores)


[253 275 256 267 253]
scores of the student with the highest total score: [92 88 95]


In [111]:
max_scores = np.max(ar2,axis=0)#To find the maxium 
min_scores = np.min(ar2,axis=0)#to find the minimum

print("Maximum scores in each subject:", max_scores)
print("Minimum scores in each subject:", min_scores)

Maximum scores in each subject: [92 95 95]
Minimum scores in each subject: [76 76 78]


In [112]:
ar5=np.sort(ar2,axis=1)#To sort the scores in ascending order

In [113]:
ar5

array([[78, 85, 90],
       [88, 92, 95],
       [76, 85, 95],
       [85, 90, 92],
       [76, 88, 89]])

In [114]:
ar2=np.array([[85,90,78],[92,88,95],[76,95,85],[90,85,92],[88,76,89]])
transposed_arr = ar2.T

print(transposed_arr)


[[85 92 76 90 88]
 [90 88 95 85 76]
 [78 95 85 92 89]]


In [2]:
n=int(input())
for i in range(n):
    for s in range(n-1,i,-1):
        print(" ",end=" " )
    for j in range(i+1):
        print("*",end=" ")
    print()
        
        

 8


              * 
            * * 
          * * * 
        * * * * 
      * * * * * 
    * * * * * * 
  * * * * * * * 
* * * * * * * * 


In [ ]:
stock={}
import pandas as pd
class equipment:
    def __int__():
        self.Eid=0
        self.Ename=''
        self.Ebrand=''
        self.ETquantity=0
        self.EAquantity=0

    def Add_item(self):
        self.Eid=int(input('enter the equipment id: '))
        self.Enameinput('enter the equipment name: ')
        self.Ebrandinput('enter the equipment brand: ')
        self.ETquantity=int(input('enter the equipment total quantity: '))
        self.EAquantity=int(input('enter the equipment available quaantity: '))
        stock[self.Eid]= ([self.Eid,self.Ename,self.Ebrand,self.ETquantity,self.EAquantity])
    def Remove_item(self):
        self.Eid=int(input('enter the equipments id: '))
        print(stock[self.Eid])
        stock.pop(self.Eid)

    def Update_item(self):
       self.Eid=int(input('enter the equipment id: '))
       print("Enter input valueis negative if want to decrease the items")
       self.ETquantity=int(input('enter the equipment total quantity to be update '))
       Qty=stock[self.Eid][2]+self.ETquantity
    def print_stock(self):
        df=pd.Dataframe(stock)
        print(df)
def Stock_Mangement():
 choice=0
 temp=equipment()
    while(choice!=5):
        

        
        
        
    

In [3]:
class Record:
    def __int__(self):
        self.name=""
        self.ID=0
        self.Eid=0
        self.Ename=""
        self.status=""
        self.condition=""
    def rent_Equip(self):
         self.name=input ("Enter your name: ")
        self.ID=input ("Enter your ID: ")
        self.Eid=input ("Enter  equipment ID of item you are renting: ")
        self.Ename=input stock[self.Eid][0]
        self.status="Rented"
        self.condition="Good"
if  Stock[self.Eid][3]=0:
    priint("Item not Available")
else:
        stock[self.Eid][3]=Stock[self.Eid][3]-1
        Records[self.ID]=list([ self.name,self.Eid,self.Ename,self.status,self.condition])
    def return_Equip(self):
        self.ID=int(input("Enter your ID: "))
        print("Member Id = ",self.ID)
        print("Member Name = ",Records[self.Eid][0])
        print("Equipment ID: = ",Records[self.Eid][1])
        print("Equipment Name:= ",Records[self.Eid][2])
        print("Status: ",Records[self.Eid][3])
        print("Condiion: ",Records[self.Eid][4])






        
        

SyntaxError: invalid syntax (1563486764.py, line 8)

In [ ]:
if__name__=="__main__":
 choice=0
 rec=Record()
while(choice !=5):
    print("______MENU______")
    print("1.Stock Management ")
    print("1.Rent Item ")
    print("1.Return Item")
    print("4.print Records ")
    print("5.Exit ")
    print("1.Stock Management ")
    